const weeklyData = [
  {
    week: '2주차',
    title: '우선순위 큐와 힙',
    concept: '우선순위 큐와 힙의 기본 동작을 이해하고 응용 문제를 분리해 정리',
    files: [],
    problems: [
      {
        id: '2-1',
        title: '응급실 환자 관리 프로그램',
        completed: true,
        contribution: '기존에 작성한 힙 구현을 응급실 상황에 적용할 수 있도록 입력·우선순위·출력 구조를 설계하고, GPT 검토를 통해 음수 우선순위 처리와 환자 번호 저장 방식을 검증함',
        percentage: 90,
        code: '',
      },
      {
        id: '2-2',
        title: '다익스트라 알고리즘 구현',
        completed: true,
        contribution: '검토',
        percentage: 15,
        code: '',
      },
      {
        id: '2-3',
        title: '라면 공장',
        completed: true,
        contribution: '검토',
        percentage: 15,
        code: '',
      },
    ],
  },
  {
    week: '3주차',
    title: '해시 테이블',
    concept: '해시 기반 자료구조를 이용해 탐색과 집계를 분리해 정리',
    files: [],
    problems: [
      {
        id: '3-1',
        title: '배운 내용 구현하기',
        completed: true,
        contribution: 'GPT를 이용해 자릿수 접기, 체이닝, BST+체이닝, 선형 탐사, 제곱 탐사, 이중 해싱, 재해싱 구현안을 만들고 팀 코드에 통합·검수함. 특히 제곱 탐사 상태 갱신과 재해싱 삭제 표식 문제를 확인함',
        percentage: 80,
        code: '',
      },
      {
        id: '3-2',
        title: '급식실 출석 확인',
        completed: true,
        contribution: 'GPT를 통한 요구사항 충족 여부 검토, 전체 제출본 포함 확인, 최종 실행 및 통합 검수로 교사에게 추가 해결 항목으로 인정받음',
        percentage: 60,
        code: '',
      },
      {
        id: '3-3',
        title: '두 개의 수로 특정값 만들기',
        completed: true,
        contribution: '검색 결과가 0일 때 실패로 처리되는 오류를 GPT 검토와 반례로 확인하고, is not None 조건으로 수정하도록 제안해 실제 수정까지 연결함',
        percentage: 100,
        code: '',
      },
      {
        id: '3-4',
        title: '숫자 카드 개수 구하기',
        completed: true,
        contribution: '전체 코드 검수 범위에 포함하여 누락 여부, 입출력 조건, 제출본 포함 여부를 확인하고 팀 해결 결과로 인정받음',
        percentage: 40,
        code: '',
      },
    ],
  },
  {
    week: '4주차',
    title: '문자열 탐색',
    concept: '문자열 매칭과 부분 문자열 성질을 분리하여 분석',
    files: [],
    problems: [
      { id: '4-1', title: '배운 내용 구현하기', completed: true, contribution: '검토', percentage: 15, code: '' },
      { id: '4-2', title: '문자열 내 최소 반복 단위', completed: true, contribution: '검토', percentage: 15, code: '' },
      { id: '4-3', title: '최장 공통 부분 구하기', completed: true, contribution: '검토', percentage: 15, code: '' },
    ],
  },
  {
    week: '5주차',
    title: '알고리즘 설계와 성능 분석',
    concept: '시간복잡도와 탐색, 정렬, DP 응용 문제를 개별 항목으로 분리',
    files: [],
    problems: [
      { id: '5-1', title: '시간복잡도 구하기', completed: true, contribution: '검토', percentage: 15, code: '' },
      {
        id: '5-2',
        title: '합이 k인 두 수 만들기',
        completed: true,
        contribution: '해시 탐색 코드에서 0 반환값이 거짓으로 평가되는 반례를 확인하고, 목표 합을 찾는 조건을 is not None으로 고쳐야 한다는 수정안을 제시함',
        percentage: 100,
        code: '',
      },
      { id: '5-3', title: '성적 상위 k명 뽑기', completed: true, contribution: '검토', percentage: 15, code: '' },
      { id: '5-4', title: '계단 오르기', completed: true, contribution: '검토', percentage: 15, code: '' },
      { id: '5-5', title: '가장 가까운 두 수', completed: true, contribution: '검토', percentage: 15, code: '' },
      { id: '5-6', title: '섬의 개수 세기', completed: true, contribution: '검토', percentage: 15, code: '' },
    ],
  },
  {
    week: '6주차',
    title: '탐욕 알고리즘',
    concept: '그리디 선택 기준과 MST, 허프만 코딩을 문제별로 분리',
    files: [],
    problems: [
      {
        id: '6-1',
        title: '거스름돈 문제',
        completed: true,
        contribution: '발표 담당은 아니지만 팀 전체 제출 코드 검수 과정에서 정상 입력 작동 여부와 잘못된 입력 처리 방식을 확인함',
        percentage: 15,
        code: '',
      },
      {
        id: '6-2',
        title: '도시 MST 만들고, 분할하기',
        completed: true,
        contribution: '[발표 담당] Kruskal 기반 MST 구성, 가장 비용이 큰 간선 제거, 두 구역 분리 결과와 테스트 케이스를 GPT로 검증해 발표자료를 준비함',
        percentage: 100,
        code: '',
      },
      {
        id: '6-3',
        title: 'Prim 알고리즘',
        completed: true,
        contribution: '[발표 담당] Prim의 우선순위 큐 구현, 컷 속성 정당성, Kruskal과의 비교, 시간복잡도와 발표 흐름을 GPT와 함께 체계적으로 준비함',
        percentage: 100,
        code: '',
      },
      {
        id: '6-4',
        title: '허프만 코딩',
        completed: true,
        contribution: '[발표 담당] 빈도가 낮은 두 노드 선택, prefix-free 코드 생성 원리, 실행 예시 부족 문제를 GPT 검수로 확인하고 발표 설명을 보완함',
        percentage: 85,
        code: '',
      },
      {
        id: '6-5',
        title: '큰 수 만들기',
        completed: true,
        contribution: '발표 담당은 아니지만 전체 제출 코드 검수에서 스택 기반 구현의 정상 동작 여부를 확인함',
        percentage: 15,
        code: '',
      },
    ],
  },
  {
    week: '7주차',
    title: '분할 정복 알고리즘',
    concept: '이진 탐색부터 쿼드 트리와 최근접 점 쌍까지 개별 주제로 정리',
    files: [],
    problems: [
      {
        id: '7-1',
        title: '이진탐색',
        completed: true,
        contribution: '분할정복 1~6번 전체 검수의 일부로 입력값, 탐색 대상 처리, 찾은 위치와 실패 출력 형식이 문제 요구에 맞는지 확인하고 보완 방향을 정리함',
        percentage: 80,
        code: '',
      },
      {
        id: '7-2',
        title: '수식과 괄호 삽입',
        completed: true,
        contribution: '수식 분할, 연산자와 숫자 분리, 부분 문제 결과 조합, 요구 출력과 주석에서 분할·정복·결합 과정이 드러나는지 GPT로 검수함',
        percentage: 80,
        code: '',
      },
      {
        id: '7-3',
        title: '학급회장 찾기',
        completed: true,
        contribution: '분할정복을 이용한 과반수 후보 탐색 코드가 후보 검출 뒤 실제 과반수인지 다시 세는 검증 과정을 포함하는지 확인함',
        percentage: 80,
        code: '',
      },
      {
        id: '7-4',
        title: '쿼드 트리',
        completed: true,
        contribution: '영역 값 일치 시 재귀 종료, 네 사분면 분할, 최초 호출 범위와 출력 형식이 요구사항에 맞는지 여러 차례 GPT로 비교·검증함',
        percentage: 80,
        code: '',
      },
      {
        id: '7-5',
        title: '최근접 점 쌍',
        completed: true,
        contribution: 'x좌표 정렬, 좌우 부분 문제 해결, 중앙 strip 검사, O(n²)와 O(n log n) 비교가 코드와 주석에 드러나는지 검토하고 보완점을 정리함',
        percentage: 80,
        code: '',
      },
      {
        id: '7-6',
        title: '광고 가성비 챙기기',
        completed: true,
        contribution: '선택 구간, 계산된 가성비 또는 이익, 최종 최적값, 입력 형식과 분할정복 과정 설명이 누락되지 않도록 GPT 채점 결과를 바탕으로 보완 대상을 정리함',
        percentage: 80,
        code: '',
      },
    ],
  },
  {
    week: '8주차',
    title: '동적 계획법',
    concept: 'DP 점화식과 상태 분리를 문제 단위로 정리',
    files: [],
    problems: [
      {
        id: '8-1',
        title: '계단 오르기 구현',
        completed: true,
        contribution: '계단 오르기 점화식 f(n)=f(n-1)+f(n-2), 피보나치와의 관계, n=100 결과, 시간복잡도와 공간복잡도를 GPT로 검증함',
        percentage: 70,
        code: '',
      },
      {
        id: '8-2',
        title: '최장 공통 부분 수열 구현',
        completed: true,
        contribution: '제출 코드가 PDF 요구와 다르다는 점을 발견하고, DP 표에서 우선 방향을 따라 하나의 LCS를 역추적하는 방식으로 수정 방향을 정리함',
        percentage: 90,
        code: '',
      },
      { id: '8-3', title: '최대 서브 배열', completed: true, contribution: '검토', percentage: 15, code: '' },
      {
        id: '8-4',
        title: '집 도둑',
        completed: true,
        contribution: 'House Robber 유형의 dp[i]=max(dp[i-1], dp[i-2]+nums[i]) 점화식을 GPT로 확인하고 인접 선택 불가 조건의 상태 전이를 검토함',
        percentage: 60,
        code: '',
      },
      {
        id: '8-5',
        title: '박람회 부스 배치',
        completed: true,
        contribution: '0-1 배낭형 배치 문제의 DP 표, 점화식, 선택 여부 비교, 역추적 방식과 탐욕법으로 최적해를 보장하지 못하는 이유를 GPT로 검증함',
        percentage: 85,
        code: '',
      },
      {
        id: '8-6',
        title: '상점 받기 게임',
        completed: true,
        contribution: '격자 선택형 DP에서 열별 선택 상태를 나누고 비트마스크로 가능한 상태를 표현하는 방식을 GPT로 검토함',
        percentage: 60,
        code: '',
      },
    ],
  },
  {
    week: '9주차',
    title: '백트래킹',
    concept: '탐색 가지치기와 완전탐색 문제를 개별 항목으로 정리',
    files: [],
    problems: [
      { id: '9-1', title: '미로 탈출하기 구현', completed: true, contribution: '검토', percentage: 15, code: '' },
      {
        id: '9-2',
        title: '지도 색칠하기 구현',
        completed: true,
        contribution: '서울시 25개 구 인접 딕셔너리를 구성하고, degree heuristic을 적용한 4색 정리 확장 시뮬레이터를 GPT 보조로 구현·검증·개선하여 팀 제출물에 통합함',
        percentage: 100,
        code: '',
      },
      { id: '9-3', title: '순열 생성', completed: true, contribution: '검토', percentage: 15, code: '' },
      {
        id: '9-4',
        title: '스도쿠 풀기',
        completed: true,
        contribution: '4×4 스도쿠 백트래킹 코드를 구현하고 행·열·2×2 박스 검사, 빈칸 목록, 실패 시 원상복구 과정을 팀 채팅에 공유하며 원리를 설명함',
        percentage: 100,
        code: '',
      },
      { id: '9-5', title: '숫자 골라 최대 합 만들기', completed: true, contribution: '검토', percentage: 15, code: '' },
    ],
  },
];

export const dummyData = weeklyData.flatMap((week) =>
  week.problems.map((problem) => ({
    week: week.week,
    weekTitle: week.title,
    weekConcept: week.concept,
    files: week.files,
    ...problem,
  }))
);

export const weeklySummary = weeklyData;
